services:

  backend:
    image: avni20/course-api:latest
    container_name: backend-container
    ports:
      - "8000:8000"
    networks:
      - backend-network

  frontend:
    image: avni20/courses_front:latest
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
